name: gawlah_services
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:





  flutter:
    sdk: flutter


  geolocator: '^5.2.1'
  font_awesome_flutter: ^8.7.0
  json_serializable: ^3.2.5
  firebase_database: ^3.1.3
  flutter_tts: ^0.8.7
  flutter_google_places: ^0.2.3
  google_maps_flutter: ^0.5.24+1
  toast: ^0.1.5
  flutter_statusbarcolor: ^0.2.3
  flutter_rating_bar: ^1.1.0
  google_maps_webservice: ^0.0.16
  url_launcher: ^5.4.2
  location : ^2.3.5
  uuid: '^2.0.4'
  http: ^0.12.0+4
  dio: ^3.0.8
  permission_handler: '^4.2.0+hotfix.3'
  google_map_polyline: ^0.2.0+1
  google_places_picker: ^2.1.0+2
  geocoder: ^0.2.1
  sliver_fab: ^1.0.0
  cloud_firestore: ^0.13.2+3
  #flutter_google_places_autocomplete: ^0.1.3
  place_picker: ^0.9.11
  #permission: ^0.1.5
  map_overlay: ^0.0.1
  fluttertoast: ^3.1.3

  cupertino_icons: ^0.1.2
 # flutter_geofire: ^1.0.3
  provider: ^4.0.4
  #geoflutterfire: ^2.1.0
 


dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - images_and_icons/ic_distance.png

     - images_and_icons/ic_gravity.png
     - images_and_icons/moon.png
     - images_and_icons/gawlah.png
     - images_and_icons/g_transparent.png


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
